version: '3.8'

services:
  php_apache:
    container_name: php_apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www           # 网站根目录
      - apache-config:/etc/apache2  # Apache 配置目录
      - php-config:/usr/local/etc/php  # PHP 配置目录
    ports:
     - "80:80"                       # 映射端口 
     - "443:443"                      
    restart: always                    # 容器随 Docker 启动


volumes:
  php-config: 
  apache-config:
                                                                       