services:
  apache:
    build: ./apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./apache/config/vhost.conf:/usr/local/apache2/conf/extra/vhost.conf
      - ./apache/config/httpd-mpm.conf:/usr/local/apache2/conf/extra/httpd-mpm.conf
      - ./apache/config/httpd-default.conf:/usr/local/apache2/conf/extra/httpd-default.conf
      - ./apache/logs:/usr/local/apache2/logs
    depends_on:
      - php56
      - php74
    restart: always                    

  php56:
    build: ./php56
    container_name: php56
    volumes:
      - ./www:/var/www/html
      - ./php56/config/php.ini:/usr/local/etc/php/php.ini  
      - ./php56/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf  # php-fpm 配置目录
    restart: always                    

  php74:
    build: ./php74
    container_name: php74
    volumes:
      - ./www:/var/www/html
      - ./php74/config/php.ini:/usr/local/etc/php/php.ini  
      - ./php74/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf  # php-fpm 配置目录
    restart: always                    

